## 开发环境

server:
  port: 8081

## Spring组件配置
spring:
  ## Redis配置参数
  redis:
    database: 2
    ## 192.168.1.134
    host: 192.168.1.130
    ## redis服务器密码，默认是没有的
    password: ''
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    port: 6379
    timeout: 0