## \u5F00\u53D1\u73AF\u5883

server:
  port: 8081

## Spring\u7EC4\u4EF6\u914D\u7F6E
spring:
  ## Redis\u914D\u7F6E\u53C2\u6570
  redis:
    database: 2
    host: 192.168.1.130
    password: ''
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    port: 6379
    timeout: 0